# Mostly same configs/models/mmbt/defaults.yaml config
includes:
- ./defaults.yaml

model_config:
  concat_bow:
    # Either pretraining or classification
    bert_model_name: bert-base-uncased
    direct_features_input: false
    freeze_text: false
    freeze_modal: false
    freeze_complete_base: false
    finetune_lr_multiplier: 1
    # Dimension of the embedding finally returned by the modal encoder
    modal_hidden_size: 2048
    # Dimension of the embedding finally returned by the text encoder
    text_hidden_size: 300
    # Used when classification head is activated
    num_labels: 2
    # Number of features extracted out per image
    # In case of resnet152, this is same as num_output_features passed to the encoder
    num_features: 100

    modal_encoder:
      type: resnet152
      params:
        pretrained: true
        pool_type: avg
        num_output_features: 1

    text_encoder:
      type: embedding
      params:
        operator: sum
        embedding_params:
          type: vocab
          params:
            type: intersected
            embedding_name: glove.6B.300d
            embedding_dim: 300
            data_dir: ${env.data_dir}
            vocab_file: vocabs/vocabulary_100k.txt

    classifier:
      type: mlp
      params:
        in_dim: 205100
        out_dim: 2
        hidden_dim: 768
        num_layers: 0
