includes:
- ../../../../mmf/configs/datasets/coco2017/masked.yaml
- ../../../../mmf/configs/datasets/flickr30k/masked.yaml
- ../../../../mmf/configs/datasets/localized_narratives/masked.yaml

model_config:
  visual_bert:
    training_head_type: pretraining

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 11000

training:
  batch_size: 32
  lr_scheduler: true
  num_workers: 0
  # Don't forget to update schedule_attributes if you update this
  max_updates: 88000
  find_unused_parameters: true

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
