model_config:
  mmf_bert:
    combine_embeddings: true
    model_data_dir: ${env.data_dir}
    bert_model_name: bert-base-uncased
    training_head_type: pretraining
    visual_embedding_dim: 2048
    special_visual_initialize: true
    hard_cap_seq_len: null
    cut_first: text
    embedding_strategy: plain
    bypass_transformer: false
    output_attentions: false
    output_hidden_states: false
    text_only: false
    random_initialize: false
    pretrained_bert: true
    image_intra_attention: true
    freeze_base: false
    finetune_lr_multiplier: 1
    image_feature_embeddings:
    - embed_dim: 768
      kdim: 768
      vdim: 768
      num_heads: 8
      dropout: 0.1
    image_feature_dim: 2048
    image_feature_projection:
      module: linear
      in_dim: 2048
      out_dim: 768
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: detectron/resnext152_fc6/fc7_b.pkl
        weights_file: detectron/resnext152_fc6/fc7_w.pkl
        model_data_dir: ${model_config.mmf_bert.model_data_dir}
    image_text_modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 768
    image_feature_attentions:
    - embed_dim: 768
      kdim: 768
      vdim: 768
      num_heads: 8
      dropout: 0.1
    text_embeddings:
    - embed_dim: 768
      kdim: 768
      vdim: 768
      num_heads: 8
      dropout: 0.1
