includes:
- ./defaults.yaml

dataset_config:
  textcaps:
    zoo_requirements:
    - textvqa.defaults
    - textcaps.defaults
    annotations:
      val:
      - textcaps/defaults/annotations/imdb_val_filtered_by_image_id.npy

model_config:
  butd: &butd
    inference:
      type: beam_search
      params:
        beam_length: 5

training:
  batch_size: 1
