includes:
- ./defaults.yaml

dataset_config:
  textvqa:
    use_images: false
    use_features: true
    zoo_requirements:
    - textvqa.defaults
    - textvqa.ocr_en
    - stvqa.defaults
    - stvqa.ocr_en
    features:
      train:
      - textvqa/defaults/features/open_images/detectron.lmdb,textvqa/ocr_en/features/ocr_en_frcn_features.lmdb
      - stvqa/defaults/features/detectron.lmdb,stvqa/ocr_en/features/ocr_en_frcn_features.lmdb
    annotations:
      train:
      - textvqa/defaults/annotations/imdb_train_ocr_en.npy
      - stvqa/defaults/annotations/imdb_subtrain.npy
