includes:
- ../vqa2/defaults.yaml
dataset_config:
  visual_genome:
    return_scene_graph: false
    return_objects: false
    return_relationships: false
    return_features_info: false

evaluation:
  metrics:
  - vqa_accuracy

training:
  early_stop:
    criteria: vqa2/vqa_accuracy
    minimize: false

model_config:
  multihead:
    model_data_dir: ${env.data_dir}
    losses:
    - type: logit_bce
    classifier:
      type: logit
      params:
        img_hidden_dim: 1024
        text_hidden_dim: 300
    image_feature_dim: 2048
    image_feature_encodings:
    - type: finetune_faster_rcnn_fpn_fc7
      params:
        bias_file: models/detectron.defaults/fc7_b.pkl
        weights_file: models/detectron.defaults/fc7_w.pkl
    - type: default
      params: {}
    image_feature_projections:
    - type: projection
      params:
        module: linear
        out_dim: 1024
    - type: projection
      params:
        module: linear
        out_dim: 1024
    image_text_modal_combine:
      type: non_linear_element_multiply
      params:
        dropout: 0
        hidden_dim: 1000
    text_embeddings:
    - type: attention
      params:
        hidden_dim: 1024
        num_layers: 1
        conv1_out: 512
        conv2_out: 2
        dropout: 0
        embedding_dim: 300
        kernel_size: 1
        padding: 0
    image_feature_embeddings:
    - num_heads: 8
      dropout: 0.1
