model_config:
  mmf_bert:
    training_head_type: visual_entailment
    losses:
    - type: cross_entropy

dataset_config:
  visual_entailment:
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 6000
    num_training_steps: 60000

evaluation:
  metrics:
  - accuracy

training:
  early_stop:
    criteria: visual_entailment/accuracy
    minimize: false
