includes:
- ./masked.yaml

optimizer:
  type: adam_w
  params:
    lr: 1e-4
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: ${training.max_updates}

training:
  batch_size: 480
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 11000
