model_config:
  unimodal_text:
    bert_model_name: bert-base-uncased
    text_hidden_size: 768
    num_labels: 2
    text_encoder:
      type: transformer
      params:
        bert_model_name: ${model_config.unimodal_text.bert_model_name}
        hidden_size: 768
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false

    classifier:
      params:
        in_dim: 768
