model_config:
  visft:
    base_args:
      lr_backbone: 0
      backbone: EVA-CLIP-5B
      backbone_dir: path/EVA02_CLIP_E_psz14_plus_s9B_Visual.pt
      grad_checkpointing: false
      num_queries:
        detection:
          detection_coco: 100
      share_decoders: false
      decoder_hidden_dim: 256
      dilation: true
      use_task_embedding_in_img_encoder: true
      use_task_embedding_in_lang_encoder: true
    losses:
    - logit_bce
    # initialize the ResNet convnet backbone from DETR
    base_ckpt_path: ''
    base_ckpt_load_backbone_only: true

evaluation:
  metrics:
  - coco_caption_bleu4

optimizer:
  type: adam_w  # HuggingFace transformer's AdamW
  enable_state_sharding: false
  params:
    lr: 4e-4
    eps: 1e-8
    weight_decay: 1e-4

scheduler:
  type: warmup_cosine
  params:
    num_warmup_steps: 2000
    num_training_steps: ${training.max_updates}

training:
  num_workers: 2
  # log_interval: 5
  # these are mostly the same as in COCO detection training
  clip_norm_mode: all
  clip_gradients: true
  max_grad_l2_norm: 0.1
  lr_scheduler: true
  lr_ratio: 0.1
  max_updates: 100000
  checkpoint_interval: 1000
  evaluation_interval: 100005
  dataset_size_proportional_sampling: false
  early_stop:
    enabled: false
    criteria: coco/coco_caption_bleu4
    minimize: false
  stdout_capture: false
  find_unused_parameters: true

checkpoint:
  max_to_keep: 100
